---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
options(scipen = 999)
theme_set(theme_light())

history_gdp <- read_csv("data/2018-10-27_chinese-century/inputs/gdp.csv") %>% select(-X1)
maddison_regions <- read_csv("data/2018-11-03-war-fighting/source_data/maddison_economic_data/maddison_cleaned_regions.csv")
```

```{r}
# Plotting gross GDP

maddison_regions %>% 
  filter(year >= 1950, 
         year != 2017) %>% 
  mutate(gross_gdp = gdp_per_capita * population) %>% 
  ggplot(aes(year, gross_gdp, color = region)) + 
  geom_line() + 
  expand_limits(y = 0) + 
  scale_x_continuous(limits = c(1950, 2018), 
                     bre)
  scale_y_continuous(labels = scales::dollar_format()) + 
  labs(title = "Figure. Aggregate GDP across regions in 1950-2017", 
       x = "Year", 
       y = "GDP")
```

```{r}
# Plotting GDP percapita

maddison_regions %>% 
  filter(year >= 1950, 
         year != 2017) %>% 
  ggplot(aes(year, gdp_per_capita, color = region)) + 
  geom_line() + 
  expand_limits(y = 0)

```

```{r}
 maddison_regions %>% 
  filter(year >= 1950, 
         year != 2017) %>% 
  mutate(gross_gdp = gdp_per_capita * population) %>% 
  group_by(year) %>% 
  mutate(share_gdp = gross_gdp / sum(gross_gdp)) %>% 
  ggplot(aes(year, share_gdp, color = region)) + 
  geom_line() + 
  scale_y_continuous(limits = c(0, 0.7))

```

```{r}
 maddison_regions %>% 
  filter(year >= 1950, 
         year != 2017) %>% 
  mutate(gross_gdp = gdp_per_capita * population) %>% 
  group_by(year) %>% 
  mutate(share_gdp = gross_gdp / sum(gross_gdp)) %>% 
  ggplot(aes(year, share_gdp, fill = region)) + 
  geom_col() + 
  expand_limits(y = 0)
```
```{r}
# Plotting long-term economic trend

history_gdp %>% filter(year > 1, 
                       iso %in% c("CHN", "IND", "USA", "JPN", "RUS", "GBR")) %>% 
  mutate(gdp.pct.share = gdp.pct.share / 100) %>% 
  ggplot(aes(year, gdp.pct.share, color = iso)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format()) +
  theme(legend.title = element_blank()) + 
  labs(x = "Year",
       y = "Share of Total Global GPD", 
       caption = "Source: Madisson country data")
```

```{r}
library(readxl)

maddison_country <- read_excel("data/2018-11-03-war-fighting/source_data/maddison_economic_data/maddison_country_data.xlsx", sheet = 2) %>% mutate(rgdp_gross = rgdpnapc * pop)

maddison_country %>% filter(country == "China", 
                            year >= 1950) %>% 
  select(country, year, rgdp_gross, cgdppc) %>% 
  gather(metric, value, rgdp_gross, cgdppc) %>% 
  mutate(metric = fct_recode(metric, "GDP" = "rgdp_gross", "GDP per capita" = "cgdppc")) %>% 
  ggplot(aes(year, value)) + 
  geom_line() + 
  scale_x_continuous(limits = c(1950, 2020), 
                     breaks = seq(1950, 2020, 10)) +
  facet_wrap(~ metric, scales = "free") + 
  labs(x = "Year", 
       y = "", 
       caption = "Source: Madision country data")
  
```
```{r}
library(grid)
library(ggrepel)

maddison_country %>% filter(country == "China", 
                            year >= 1950) %>% 
  mutate(gdp_growth = (rgdp_gross - lag(rgdp_gross, 1)) / lag(rgdp_gross, 1)) %>% 
  ggplot(aes(year, gdp_growth)) + 
  geom_point(color = "black", size = 2) +
  geom_line(color = "blue", size = 0.5) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_vline(xintercept = 1978, linetype = "dashed") +
  scale_x_continuous(limits = c(1950, 2017), 
                     breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2017)) +
  scale_y_continuous(labels = scales::percent_format()) + 
  annotate("rect", xmin = 1958, xmax = 1962, ymin = -0.2, ymax = 0.03, alpha = .3, fill = "blue") +
  annotate("rect", xmin = 1966, xmax = 1976, ymin = -0.05, ymax = 0.15, alpha = .3, fill = "blue") + 
  annotate("rect", xmin = 1989, xmax = 1990, ymin = -.03, ymax = 0.03, alpha = .3, fill = "blue") + 
  annotate("segment", x = 1968, xend = 1962, y = -.15, yend = -.18, color = "red", size = 1, arrow = arrow(type = "closed", length = unit(1.5, "mm"))) + 
  annotate("segment", x = 1976, xend = 1972, y = 0.2, yend = .15, color = "red", size = 1, arrow = arrow(type = "closed", length = unit(1.5, "mm"))) +
  annotate("segment", x = 1995, xend = 1990, y = -.1, yend = -.03, color = "red", size = 1, arrow = arrow(type = "closed", length = unit(1.5, "mm"))) + 
  annotate("segment", x = 1978, xend = 1997, y = .16, yend = .16, color = "blue", size = 3, alpha = .8, arrow = arrow(type = "closed", length = unit(5, "mm"))) +
  annotate("text", x = 1971, y = -.13, label = "Great Leap Forward") +
  annotate("text", x = 1977, y = .21, label = "Cultural Revolution") +
  annotate("text", x = 1996, y = -.11, label = "Tiananmen Incident") +
  annotate("text", x = 1999, y = .19, size = 4, label = "The era of reform and opening") +
  labs(x = "Year", 
       y = "GDP growth", 
       caption = "Source: Maddison country data")
```

```{r}
maddison_country %>% 
  filter(year >= 1950, country %in% c("Japan", 
                                      "China", 
                                      "Republic of Korea", 
                                      "D.P.R of Korea", 
                                      "China, Hong Kong SAR",
                                      "Taiwan, Province of China", 
                                      "Mongolia",
                                      "Malaysia", 
                                      "Myanmar", 
                                      "Philippines", 
                                      "Thailand", 
                                      "Singapore", 
                                      "Cambodia",
                                      "Vietnam (North)", 
                                      "Vietnam (South)", 
                                      "Viet Nam", 
                                      "Indonesia", 
                                      "Lao People's DR")) %>% 
  mutate(subregion = ifelse(country %in% c("Japan", 
                                           "China", 
                                           "Republic of Korea", 
                                           "D.P.R of Korea", 
                                           "China, Hong Kong SAR",
                                           "Taiwan, Province of China", 
                                           "Mongolia"), "Northeast", "Southeast")) %>% 
  group_by(year, subregion) %>% 
  summarize(total_gdp = sum(rgdp_gross)) %>% 
  ggplot(aes(year, total_gdp, color = subregion)) +
  geom_line()
  
```
```{r}
uspd_conflict <- read_csv("data/2018-11-03-war-fighting/source_data/UCDP_conflict_data/UCDP_18.1_state_conflict_data.csv")

```

```{r}
uspd_conflict %>% filter(side_a == "Government of China")
```
# Plotting the temporal trend in gini coefficient

```{r}
china_gini <- read_excel("china_gini-coefficient.xlsx")

china_gini %>% 
  ggplot(aes(year, value)) + 
  geom_line(size = 1) + 
  scale_x_continuous(limits = c(2000, 2017), 
                     breaks = seq(2000, 2017, 1), 
                     labels = c(1985, 1990, 1998, 2003, "04", "05", "06", "07", "08", "09", seq(10, 17, 1))) +
  scale_y_continuous(limits = c(0.3, 0.5)) + 
  geom_text_repel(aes(label = value), hjust = 1, vjust =1) + 
  labs(x = "Year", 
       y = "")
```

```{r}
library(haven)

gperc_w_China <- read_dta("gperc_w_China.dta")
```

