---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
options(scipen = 999)
theme_set(theme_light())

history_gdp <- read_csv("data/2018-10-27_chinese-century/inputs/gdp.csv") %>% select(-X1)
maddison_regions <- read_csv("data/2018-11-03-war-fighting/source_data/maddison_economic_data/maddison_cleaned_regions.csv")
```

# Gini coefficient
```{r}
china_gini <- read_excel("china_gini-coefficient.xlsx")

china_gini %>% 
  ggplot(aes(year, value)) + 
  geom_line(size = 1) + 
  scale_x_continuous(limits = c(2000, 2017), 
                     breaks = seq(2000, 2017, 1), 
                     labels = c(1985, 1990, 1998, 2003, "04", "05", "06", "07", "08", "09", seq(10, 17, 1))) +
  scale_y_continuous(limits = c(0.3, 0.5)) + 
  geom_text_repel(aes(label = value), hjust = 1, vjust =1) + 
  labs(x = "Year", 
       y = "")
```

```{r}
library(haven)

gperc_w_China <- read_dta("gperc_w_China.dta")
```

```{r}
library(tidyverse)
library(janitor)

youth_unemp <- read_csv("OECD_youth-unemployment_china.csv") %>% clean_names()

youth_unemp %>% 
  filter(time == 2018) %>% 
  mutate(selected_countries = ifelse(location %in% c("JPN", "KOR", "CHN", "USA", "GBR", "EU28", "OECD"), "N", "Y")) %>% 
  mutate(location = fct_reorder(location, value)) %>% 
  ggplot(aes(location, value, fill = selected_countries)) + 
  geom_col() +
  theme(legend.position = "none") +
  labs(title = "Distribution of Youth Unemployment rates in 2018", 
       x = "", 
       y = "Youth unemployment rates")
  
```

