---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(scales)
theme_set(theme_light())
options(scipen = 999)

taiwan_china <- read_csv("taiwan-china-trade.csv") 
china_taiwan <- read_csv("china-trade-taiwan.csv") %>% mutate(pct_china_export = total_export_taiwan / total_export) %>% filter(year > 1998)
```

```{r}
taiwan_china_pct <- taiwan_china %>% 
  select(year, total_export, total_export_china) %>% 
  filter(year > 1998) %>% 
  mutate(pct_taiwan_export = total_export_china / total_export) 

# Plotting
taiwan_china_pct %>% left_join(china_taiwan, by = "year") %>% 
  gather(pct_trade, value, pct_taiwan_export, pct_china_export) %>% 
  ggplot(aes(year, value, color = pct_trade)) +
  geom_point() + 
  geom_line() + 
  scale_y_continuous(labels = percent_format()) +
  theme(legend.position = "top", 
        legend.title = element_blank()) +
  scale_color_discrete(labels = c("% of China's export to Taiwan", "% of Taiwan's export to China")) +
  labs(title = "Figure. Uneven Reliance", 
       subtitle = "Trade data shows Taiwan needs China (a lot) more", 
       x = "", 
       y = "", 
       caption = "Source: Ministry of Finance, ROC; China Statistics Yearbook")

```

# Analyzing TNSS focusing on changing perceptions of the China threat and its implications for attitudes toward future independence
```{r}
library(haven)
library(janitor)

taiwan_security_2019 <- read_sav("2019_TNSS/PP199711.sav") %>% clean_names()
taiwan_security_2017 <- read_sav("2017_TNSS/PP1797B1(ƒ¿•X™©) (1).sav") %>% clean_names()
taiwan_security_2016 <- read_sav("2016_TNSS/PP1697B1(釋出版)加權.sav") %>% clean_names()
taiwan_security_2015 <- read_sav("2015_TNSS/Sav/PP1597A1.sav") %>% clean_names()
taiwan_security_2013 <- read_sav("2013_TNSS/PP1397B1.sav") %>% clean_names()
taiwan_security_2012 <- read_sav("2012_TNSS/2012/PP1297A5.sav") %>% clean_names()
taiwan_security_2011 <- read_sav("2011_TNSS/2011/PP119721.sav") %>% clean_names() 
taiwan_security_2008 <- read_sav("2008_TNSS/2008/PP089721.sav") %>% clean_names()
taiwan_security_2005 <- read_sav("2005_TNSS/2005/pp059752.sav") %>% clean_names()
taiwan_security_2004 <- read_sav("2004_TNSS/2004/PT049750.sav") %>% clean_names()
taiwan_security_2003 <- read_sav("2002_TNSS/2003/pt0297c4.sav") %>% clean_names()
```

```{r}
taiwan_security_2019 %>% select(date, q8, q9, q14) %>% 
  mutate(q8 = factor(q8, levels = 1:4, 
                     labels = c("strongly oppose", "oppose", "support", "strongly support")), 
         q8 = fct_explicit_na(q8, na_level = "Non-reaction")) %>%
  mutate(q9 = factor(q9, levels = 1:4, 
                     labels = c("strongly oppose", "oppose", "support", "strongly support")), 
         q9 = fct_explicit_na(q9, na_level = "Non-reaction")) %>% 
  mutate(q14 = factor(q14, levels = 1:4, 
                      labels = c("Very unlikely", "Unlikely", "Likely", "Very likely")), 
         q14 = fct_explicit_na(q14, na_level = "Non-reaction")) %>% 
  rename(attack_ind = q8,
         no_attack_ind = q9, 
         ind_cause_attack = q14) %>% 
  gather(question, answer, attack_ind, no_attack_ind) %>% 
  count(question, answer, sort = T) %>% 
  ggplot(aes(answer, n)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ question) + 
  labs(title = "Conditional preference for independence", 
       x = "", 
       y = "# of respondents", 
       caption = "Source: Taiwan National Security Survey (https://sites.duke.edu/pass/taiwan-national-security-survey/)")

taiwan_security_2017 %>% select(date, q14, q15, q9) %>% 
  mutate(q14 = factor(q14, levels = 1:4, 
                     labels = c("strongly oppose", "oppose", "support", "strongly support")), 
         q14 = fct_explicit_na(q14, na_level = "Non-reaction")) %>%
  mutate(q15 = factor(q15, levels = 1:4, 
                     labels = c("strongly oppose", "oppose", "support", "strongly support")), 
         q15 = fct_explicit_na(q15, na_level = "Non-reaction")) %>% 
  mutate(q9 = factor(q9, levels = 1:4, 
                      labels = c("Very unlikely", "Unlikely", "Likely", "Very likely")), 
         q9 = fct_explicit_na(q9, na_level = "Non-reaction")) %>% 
  rename(attack_ind = q14,
         no_attack_ind = q15, 
         ind_cause_attack = q9) 
  


```

```{r}
taiwan_security_2019 %>% select(date, q8, q9, q14) %>% 
  mutate(q8 = factor(q8, levels = 1:4, 
                     labels = c("strongly oppose", "oppose", "support", "strongly support")), 
         q8 = fct_explicit_na(q8, na_level = "Non-reaction")) %>%
  mutate(q9 = factor(q9, levels = 1:4, 
                     labels = c("strongly oppose", "oppose", "support", "strongly support")), 
         q9 = fct_explicit_na(q9, na_level = "Non-reaction")) %>% 
  mutate(q14 = factor(q14, levels = 1:4, 
                      labels = c("Very unlikely", "Unlikely", "Likely", "Very likely")), 
         q14 = fct_explicit_na(q14, na_level = "Non-reaction")) %>% 
  rename(attack_ind = q8,
         no_attack_ind = q9, 
         ind_cause_attack = q14) %>%  
  gather(question, answer, attack_ind, no_attack_ind) %>% 
  count(question, answer, ind_cause_attack, sort = T) %>% 
  ggplot(aes(answer, n, fill = ind_cause_attack)) +
  geom_col() +
  coord_flip() +
  scale_fill_discrete(name = "Chance of attack") +
  facet_wrap(~ question) +
  labs(title = "Conditional preference for independence", 
       x = "", 
       y = "# of respondents", 
       caption = "Source: Taiwan National Security Survey (https://sites.duke.edu/pass/taiwan-national-security-survey/)")
```

# Question regarding the attitude toward economic relationship with mainland
```{r}
econ_2019 <- taiwan_security_2019 %>% select(date, q3) %>% 
  mutate(q3 = factor(q3, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q3 = fct_explicit_na(q3, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q3) %>% 
  mutate(year = 2019)

econ_2017 <- taiwan_security_2017 %>% select(date, q3) %>% 
  mutate(q3 = factor(q3, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q3 = fct_explicit_na(q3, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q3) %>% 
  mutate(year = 2017)

econ_2016 <- taiwan_security_2016 %>% select(date, q3) %>% 
  mutate(q3 = factor(q3, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q3 = fct_explicit_na(q3, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q3) %>% 
  mutate(year = 2016)

econ_2015 <- taiwan_security_2015 %>% select(date, q3) %>% 
  mutate(q3 = factor(q3, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q3 = fct_explicit_na(q3, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q3) %>% 
  mutate(year = 2015)

econ_2013 <- taiwan_security_2013 %>% select(date, q7) %>% 
  mutate(q7 = factor(q7, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q7 = fct_explicit_na(q7, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q7) %>% 
  mutate(year = 2013)

econ_2012 <- taiwan_security_2012 %>% select(date, q7) %>% 
  mutate(q7 = factor(q7, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q7 = fct_explicit_na(q7, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q7) %>% 
  mutate(year = 2012)

econ_2011 <- taiwan_security_2011 %>% select(date, q7) %>% 
  mutate(q7 = factor(q7, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q7 = fct_explicit_na(q7, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q7) %>% 
  mutate(year = 2011)

econ_2008 <- taiwan_security_2008 %>% select(date, q3) %>% 
  mutate(q3 = factor(q3, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q3 = fct_explicit_na(q3, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q3) %>% 
  mutate(year = 2008)

econ_2005 <- taiwan_security_2005 %>% select(date, q3) %>% 
  mutate(q3 = factor(q3, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q3 = fct_explicit_na(q3, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q3) %>% 
  mutate(year = 2005)

econ_2004 <- taiwan_security_2004 %>% select(date, q5) %>% 
  mutate(q5 = factor(q5, levels = 1:2, 
                     labels = c("strengthen", "weaken")), 
         q5 = fct_explicit_na(q5, na_level = "Non-reaction")) %>% 
  rename(econ_relations = q5) %>% 
  mutate(year = 2004)

econ_years <- econ_2004 %>% bind_rows(econ_2005) %>% bind_rows(econ_2008) %>% bind_rows(econ_2011) %>% bind_rows(econ_2012) %>% bind_rows(econ_2013) %>% bind_rows(econ_2015) %>% bind_rows(econ_2016) %>% bind_rows(econ_2017) %>% bind_rows(econ_2019)

library(lubridate)

econ_years %>% mutate(year = as.character(year)) %>% 
  group_by(year) %>% 
  count(econ_relations) %>% 
  mutate(pct = n / sum(n)) %>% 
  ggplot(aes(year, pct, fill = econ_relations)) +
  geom_col() + 
  scale_y_continuous(labels = scales::percent_format()) +
  theme(legend.position = "top", 
        legend.title = element_blank()) +
  labs(title = "Do you think Taiwan should strenghten its economic relations with China?", 
       x = "", 
       y = "", 
       caption = "Source: Taiwan National Security Survery")
```
# How likely Taiwanese think China will take military action upon the declaration of independence?

```{r}

```

