---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
theme_set(theme_minimal())
options(scipen = 999)

hongkong_tourism <- read_excel("china-hongkong-tourism.xlsx") %>% mutate(pct_exp = exp_mainland / exp_total)
```

```{r}
g <- hongkong_tourism %>% 
  ggplot(aes(year, visitors_mainland)) +
  geom_line(size = 1.3) + 
  scale_x_continuous(limits = c(1995, 2017), 
                     breaks = seq(1995, 2017, 2)) +
  scale_y_continuous(limits = c(0, 50000), 
                     breaks = seq(0, 50000, 10000), 
                     labels = c("0", "10M", "20M", "30M", "40M", "50M")) + 
  labs(title = "MOST VALUABLE VISITORS", 
       subtitle = "Blue (left scale), Red (right scale)", 
       x = "", 
       y = "", 
       captions = "Source: Hong Kong Annual Digest of Statistics")

g + geom_line(data = hongkong_tourism_pct, aes(year, pct_exp * 60000), size = 1.3, color = "gray") + 
  scale_y_continuous(limits = c(0, 50000), 
                     breaks = seq(0, 50000, 10000), 
                     labels = c("0", "10M", "20M", "30M", "40M", "50M"), 
                     sec.axis = sec_axis(~ . / 60000, name = "% of mainlanders' expenditure in total consumption")) + 
  theme_bw() +
  theme(plot.title = element_text(size = 15)) +
  labs(y = "# of visitors from mainland")

hongkong_tourism %>% 
  select(-exp_mainland, -exp_total) %>%
  gather(metric, value, -year) %>% 
  ggplot(aes(year, value)) + 
  geom_point() +
  geom_line() +
  facet_wrap(~ metric, scales = "free_y")
  
  
```

```{r}
hongkong_tourism_pct <- hongkong_tourism %>% 
  filter(year > 1999)

hongkong_tourism_pct %>% 
  ggplot(aes(year, pct_exp)) + 
  geom_point() +
  geom_line(size = 1.2) + 
  expand_limits(y = 0.2) + 
  scale_x_continuous(limits = c(2000, 2017), 
                     breaks = seq(2000, 2017, 2)) +
  scale_y_continuous(limits = c(0.2, 0.8), 
                     breaks = seq(0.2, 0.8, 0.1), 
                     labels = scales::percent_format()) + 
  labs(title = "Most Valuable Visitors", 
       subtitle = "% of mainland visitors (overnight) in total consumption", 
       x = "", 
       y = "",
       caption = "Source: Hong Kong Annual Digest of Statistics")
```

```{r}
hongkong_realestate <- read_excel("his_data_2.xls", col_names = FALSE, skip = 3)
```

```{r}
library(rvest)
library(janitor)

hongkong_poll_page <- read_html("https://www.pori.hk/nationalissues/octs2taiwan")

hongkong_poll <- hongkong_poll_page %>% 
  html_node("table") %>% 
  html_table(header = NA) %>% 
  tbl_df() 

names(hongkong_poll) <- list("date", "total_sample", "sub_sample", "applicable", "not_applicable", "not_sure", "total", "net_value")

hongkong_poll <- hongkong_poll[-1, ]
```

```{r}
library(lubridate)
library(ggrepel)

hongkong_confidence <- read_excel("hongkong-confidence-one-country-two-systems.xlsx") %>% clean_names() 

key_junctures <- tibble(
  dates = c("1997-07-01", "2003-07-01", "2008-08-01", "2014-06-01"), 
  events = c("Return", "State Security Law", "Beijing Olympic", "Umbrella Movement")
)

hongkong_confidence_clean <- hongkong_confidence %>% 
  mutate(date_of_survey = dmy(date_of_survey)) %>% 
  select(-effective_sample_size, -sub_sample) %>% 
  mutate(confident = as.numeric(str_trim(str_replace(confident, "\\%", ""))), 
         not_confident = as.numeric(str_trim(str_replace(not_confident, "\\%", ""))), 
         dk_hs = as.numeric(str_trim(str_replace(dk_hs, "\\%", ""))), 
         net_value = as.numeric(str_trim(str_replace(net_value, "\\%", ""))))

hongkong_confidence_clean %>% 
  gather(Response, value, confident, not_confident, net_value) %>% 
  mutate(value = value / 100, 
         Response = fct_rev(Response)) %>% 
  ggplot(aes(date_of_survey, value, color = Response)) +
  geom_line(size = 1) + 
  geom_vline(xintercept = as.Date(key_junctures$dates), linetype = "dashed") +
  scale_y_continuous(limits = c(-0.25, 0.8), 
                     breaks = seq(-0.25, 0.8, 0.1), 
                     labels = scales::percent) +
  theme(plot.title = element_text(size = 15, face = "bold"), 
        legend.position = "bottom") +
  labs(title = "Confidence crisis?", 
       subtitle = "Question: Do you have confidence in 'one country, two systems'?",
       x = "", 
       y = "", 
       caption = "Data from HKU Public Opinion Program")
  
  
```

